### ISSUE TITLE
rr(module) only works if the present working directory is the same as the source erl file

### ISSUE THREAD

**Issue by dzntz** [erlang/erlide_eclipse#265] opened 2016-04-10 13:50 UTC
I can call modules without having to be in the same directory as the source, but this is not the case for reading records which fails unless pwd is cd'd to the location of the .erl source file.

I'm not sure if this is a flaw or not but now you know.

Great work Mr Vlad Dumitrescu!

Eclipse Version: Mars.2 Release (4.5.2) Build id: 20160218-0600
  Eclipse IDE for C/C++ Developers	4.5.2.20160218-0600	epp.package.cpp	null
  Erlang language tools IDE	0.31.0.201604090732	org.erlide.feature.group	Erlide project
  Erlide Wrangler support	0.10.3.201604090732	org.erlide.wrangler.feature.group	UKC

**Comment by vladdu** [comment] 2016-04-10 14:22
Thanks! I confess that I don't use rr() very much, so I will check how it works in the normal console and why it doesn't in the erlide console. Thanks for reporting this.

**Comment by dzntz** [comment] 2016-04-10 14:56
To clarify
rr(record_name,{foo,bar}).
will WORK!  But you have to change the directory to the location of the source file.

**Comment by vladdu** [comment] 2016-04-11 11:48
I tested and it works fine for me (: 
```
(asa@mars)4> rr(az).
[aa]
(asa@mars)5> pwd().
C:/Apps/eclipse/dsl-latest/eclipse
ok
(asa@mars)6> code:which(az).
"c:/Users/vlad/workspace/junit-workspace/asa/ebin/az.beam"
```

Please attach a sequence of commands that don't work for you.

**Comment by vladdu** [comment] 2016-08-23 19:19
I am closing this, since it works for me. Please reopen if you still have a use case that doesn't work, with details on how to reproduce.

**Closed by vladdu** 2016-08-23 19:19 UTC
Labels: wait for feedback
